export interface HeroData {
  id: number;
  name: string;
  attr: 'str' | 'agi' | 'int' | 'uni';
}

export const DOTA_HEROES: HeroData[] = [
  { id: 1, name: "Anti-Mage", attr: "agi" },
  { id: 2, name: "Axe", attr: "str" },
  { id: 3, name: "Bane", attr: "uni" },
  { id: 4, name: "Bloodseeker", attr: "agi" },
  { id: 5, name: "Crystal Maiden", attr: "int" },
  { id: 6, name: "Drow Ranger", attr: "agi" },
  { id: 7, name: "Earthshaker", attr: "str" },
  { id: 8, name: "Juggernaut", attr: "agi" },
  { id: 9, name: "Mirana", attr: "uni" },
  { id: 10, name: "Morphling", attr: "agi" },
  { id: 11, name: "Shadow Fiend", attr: "agi" },
  { id: 12, name: "Phantom Lancer", attr: "agi" },
  { id: 13, name: "Puck", attr: "uni" },
  { id: 14, name: "Pudge", attr: "str" },
  { id: 15, name: "Razor", attr: "agi" },
  { id: 16, name: "Sand King", attr: "uni" },
  { id: 17, name: "Storm Spirit", attr: "int" },
  { id: 18, name: "Sven", attr: "str" },
  { id: 19, name: "Tiny", attr: "str" },
  { id: 20, name: "Vengeful Spirit", attr: "uni" },
  { id: 21, name: "Windranger", attr: "uni" },
  { id: 22, name: "Zeus", attr: "int" },
  { id: 23, name: "Kunkka", attr: "str" },
  { id: 25, name: "Lina", attr: "int" },
  { id: 26, name: "Lion", attr: "int" },
  { id: 27, name: "Shadow Shaman", attr: "int" },
  { id: 28, name: "Slardar", attr: "str" },
  { id: 29, name: "Tidehunter", attr: "str" },
  { id: 30, name: "Witch Doctor", attr: "int" },
  { id: 31, name: "Lich", attr: "int" },
  { id: 32, name: "Riki", attr: "agi" },
  { id: 33, name: "Enigma", attr: "uni" },
  { id: 34, name: "Tinker", attr: "int" },
  { id: 35, name: "Sniper", attr: "agi" },
  { id: 36, name: "Necrophos", attr: "int" },
  { id: 37, name: "Warlock", attr: "int" },
  { id: 38, name: "Beastmaster", attr: "uni" },
  { id: 39, name: "Queen of Pain", attr: "int" },
  { id: 40, name: "Venomancer", attr: "uni" },
  { id: 41, name: "Faceless Void", attr: "agi" },
  { id: 42, name: "Wraith King", attr: "str" },
  { id: 43, name: "Death Prophet", attr: "int" },
  { id: 44, name: "Phantom Assassin", attr: "agi" },
  { id: 45, name: "Pugna", attr: "int" },
  { id: 46, name: "Templar Assassin", attr: "agi" },
  { id: 47, name: "Viper", attr: "agi" },
  { id: 48, name: "Luna", attr: "agi" },
  { id: 49, name: "Dragon Knight", attr: "str" },
  { id: 50, name: "Dazzle", attr: "int" },
  { id: 51, name: "Clockwerk", attr: "uni" },
  { id: 52, name: "Leshrac", attr: "int" },
  { id: 53, name: "Nature's Prophet", attr: "int" },
  { id: 54, name: "Lifestealer", attr: "str" },
  { id: 55, name: "Dark Seer", attr: "int" },
  { id: 56, name: "Clinkz", attr: "agi" },
  { id: 57, name: "Omniknight", attr: "str" },
  { id: 58, name: "Enchantress", attr: "int" },
  { id: 59, name: "Huskar", attr: "str" },
  { id: 60, name: "Night Stalker", attr: "str" },
  { id: 61, name: "Broodmother", attr: "uni" },
  { id: 62, name: "Bounty Hunter", attr: "agi" },
  { id: 63, name: "Weaver", attr: "agi" },
  { id: 64, name: "Jakiro", attr: "int" },
  { id: 65, name: "Batrider", attr: "uni" },
  { id: 66, name: "Chen", attr: "int" },
  { id: 67, name: "Spectre", attr: "agi" },
  { id: 68, name: "Ancient Apparition", attr: "int" },
  { id: 69, name: "Doom", attr: "str" },
  { id: 70, name: "Ursa", attr: "agi" },
  { id: 71, name: "Spirit Breaker", attr: "str" },
  { id: 72, name: "Gyrocopter", attr: "agi" },
  { id: 73, name: "Alchemist", attr: "str" },
  { id: 74, name: "Invoker", attr: "uni" },
  { id: 75, name: "Silencer", attr: "int" },
  { id: 76, name: "Outworld Destroyer", attr: "int" },
  { id: 77, name: "Lycan", attr: "uni" },
  { id: 78, name: "Brewmaster", attr: "str" },
  { id: 79, name: "Shadow Demon", attr: "int" },
  { id: 80, name: "Lone Druid", attr: "uni" },
  { id: 81, name: "Chaos Knight", attr: "str" },
  { id: 82, name: "Meepo", attr: "agi" },
  { id: 83, name: "Treant Protector", attr: "str" },
  { id: 84, name: "Ogre Magi", attr: "str" },
  { id: 85, name: "Undying", attr: "str" },
  { id: 86, name: "Rubick", attr: "int" },
  { id: 87, name: "Disruptor", attr: "int" },
  { id: 88, name: "Nyx Assassin", attr: "agi" },
  { id: 89, name: "Naga Siren", attr: "agi" },
  { id: 90, name: "Keeper of the Light", attr: "int" },
  { id: 91, name: "Io", attr: "str" },
  { id: 92, name: "Visage", attr: "uni" },
  { id: 93, name: "Slark", attr: "agi" },
  { id: 94, name: "Medusa", attr: "agi" },
  { id: 95, name: "Troll Warlord", attr: "agi" },
  { id: 96, name: "Centaur Warrunner", attr: "str" },
  { id: 97, name: "Magnus", attr: "str" },
  { id: 98, name: "Timbersaw", attr: "str" },
  { id: 99, name: "Bristleback", attr: "str" },
  { id: 100, name: "Tusk", attr: "str" },
  { id: 101, name: "Skywrath Mage", attr: "int" },
  { id: 102, name: "Abaddon", attr: "str" },
  { id: 103, name: "Elder Titan", attr: "str" },
  { id: 104, name: "Legion Commander", attr: "str" },
  { id: 105, name: "Techies", attr: "uni" },
  { id: 106, name: "Ember Spirit", attr: "agi" },
  { id: 107, name: "Earth Spirit", attr: "str" },
  { id: 108, name: "Underlord", attr: "str" },
  { id: 109, name: "Terrorblade", attr: "agi" },
  { id: 110, name: "Phoenix", attr: "str" },
  { id: 111, name: "Oracle", attr: "int" },
  { id: 112, name: "Winter Wyvern", attr: "uni" },
  { id: 113, name: "Arc Warden", attr: "agi" },
  { id: 114, name: "Monkey King", attr: "agi" },
  { id: 119, name: "Dark Willow", attr: "uni" },
  { id: 120, name: "Pangolier", attr: "agi" },
  { id: 121, name: "Grimstroke", attr: "int" },
  { id: 123, name: "Hoodwink", attr: "agi" },
  { id: 126, name: "Void Spirit", attr: "uni" },
  { id: 128, name: "Snapfire", attr: "uni" },
  { id: 129, name: "Mars", attr: "str" },
  { id: 135, name: "Dawnbreaker", attr: "str" },
  { id: 136, name: "Marci", attr: "str" },
  { id: 137, name: "Primal Beast", attr: "str" },
  { id: 138, name: "Muerta", attr: "int" },
  { id: 131, name: "Ringmaster", attr: "int" },
  { id: 145, name: "Kez", attr: "agi" }
];
